### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by Daniel-CB** [cultureboot/cultureboot.github.io#1]
3e citation : manque une image

**Comment by fzaninotto** [comment]
Bizarre: moi, j'en vois une 
![image](https://cloud.githubusercontent.com/assets/99944/25619192/4b5f5b88-2f4a-11e7-8e3e-1461ed1b5663.png)

C'est quoi ton navigateur ?

**Comment by Daniel-CB** [comment]
C'est bon, je la vois aussi
